
name: CI Angular App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    tests:
        name: Run tests
        runs-on: ubuntu-latest

        steps:
            - name: Inicio de trabajo
              run: |
                echo "Iniciando el trabajo de CI para la aplicación Angular"
                echo "Evento: ${{ github.event_name }} | Rama: ${{ github.ref }} | Actor: ${{ github.actor }}"
            # Instalar Node.js
            - name: Configurar Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18'

            # Instalar dependencias
            - name: Instalar dependencias
              working-directory: ./probando-angular
              run: npm install

            # Ejecutar pruebas
            - name: Ejecutar pruebas
              run: npm test -- --watch=false --browsers=ChromeHeadlessCI

            # Mensaje Final
            - name: Finalizar trabajo
              run: echo "Trabajo de CI para la aplicación Angular completado exitosamente"

